name: bookish
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  provider: ^4.3.2+2
  google_sign_in: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Sacramento
      fonts:
        - asset: fonts/Sacramento-Regular.ttf
    - family: Peddana
      fonts:
        - asset: fonts/Peddana-Regular.ttf
          